### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by sergey-suloev** [mripard/sunxi-mali#11]
Hello, can't build the code on 4.13.16
Here is the log:

  CC [M]  /home/sergey/Projects/drivers/sunxi/orangepipc/sunxi-mali/r6p2/src/devicedrv/mali/linux/mali_osk_timers.o
/home/sergey/Projects/drivers/sunxi/orangepipc/sunxi-mali/r6p2/src/devicedrv/mali/linux/mali_osk_timers.c: In function ‘_mali_osk_timer_setcallback’:
/home/sergey/Projects/drivers/sunxi/orangepipc/sunxi-mali/r6p2/src/devicedrv/mali/linux/mali_osk_timers.c:63:2: error: implicit declaration of function ‘timer_setup’; did you mean ‘ktime_set’? [-Werror=implicit-function-declaration]
  timer_setup(&tim->timer, callback, 0);
  ^~~~~~~~~~~
  ktime_set
cc1: some warnings being treated as errors
scripts/Makefile.build:302: recipe for target '/home/sergey/Projects/drivers/sunxi/orangepipc/sunxi-mali/r6p2/src/devicedrv/mali/linux/mali_osk_timers.o' failed
make[2]: *** [/home/sergey/Projects/drivers/sunxi/orangepipc/sunxi-mali/r6p2/src/devicedrv/mali/linux/mali_osk_timers.o] Error 1
Makefile:1512: recipe for target '_module_/home/sergey/Projects/drivers/sunxi/orangepipc/sunxi-mali/r6p2/src/devicedrv/mali' failed
make[1]: *** [_module_/home/sergey/Projects/drivers/sunxi/orangepipc/sunxi-mali/r6p2/src/devicedrv/mali] Error 2
make[1]: Leaving directory '/home/sergey/Projects/armbian/build/cache/sources/linux-mainline/linux-4.13.y'

**Comment by sergey-suloev** [comment]
Maxime, 
can we somehow make this code compile on  4.13, 1.14, 4.15 versions ? Some patches are required only for specific version of kernel and break build on other versions.

**Comment by giuliobenetti** [comment]
Fix on PR
